# Generated by Django 4.1.7 on 2023-04-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'VALUE'), (1, 'PERCENT')], default=0),
        ),
    ]
