# Generated by Django 4.1.7 on 2023-04-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created_at',)},
        ),
    ]
