# Generated by Django 4.1.7 on 2023-04-12 17:00
import os
from django.db import migrations
from faker import Faker
from django.core.files.images import ImageFile
from project.settings import BASE_DIR
from io import BytesIO
from django.db import transaction

fake = Faker()


@transaction.atomic
def start(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')

    image_path = os.path.join(BASE_DIR, 'static', 'media', 'sneaker.jpeg')
    with open(image_path, 'rb') as f:
        image_data = f.read()
    image_file = ImageFile(BytesIO(image_data), name='sneaker.jpeg')

    for _x in range(100):
        product = Product.objects.create(
            name=fake.word(),
            description=fake.sentence(),
            image=image_file,
            sku=fake.random_number(),
            price=fake.pydecimal(left_digits=3, right_digits=2, positive=True),
        )
        category, _ = Category.objects.get_or_create(name='sneakers')
        product.category.add(category)


def end():
    Product = apps.get_model('products', 'Product')
    Product.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            start,
            end
        )
    ]
