# Generated by Django 4.1.7 on 2023-04-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
